//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by IceExporter.rc
//
#define IDS_MATCACLASSNAME              4
#define IDS_CUSTOM_MATERIAL             5
#define IDS_COLOR                       6
#define IDS_SUBMAP                      7
#define IDS_SELECT_SHADER               8
#define IDS_DEFAULT_SHADER              9
#define IDS_SHADER_TYPES                10
#define IDS_FLXMATCLASSNAME             11
#define IDS_FLEXPORTER_MATERIAL         12
#define IDD_DIALOG1                     3000
#define IDC_ABOUT                       3000
#define IDD_UTILITY_PANEL               3000
#define IDD_ABOUT                       3001
#define IDC_STATUS                      3001
#define IDD_EXPORT                      3002
#define IDC_EXT_STATUS                  3002
#define IDC_PROGRESS1                   3003
#define IDD_MESSAGE                     3003
#define IDC_EXPORT                      3004
#define IDD_OPTIONS                     3004
#define IDC_OPTIONS                     3005
#define IDC_COPY                        3006
#define IDD_DIALOG2                     3006
#define IDD_ADD_USER_PROP               3008
#define IDC_EDIT                        3009
#define IDB_BITMAP1                     3009
#define IDC_NEXTPLUG                    3010
#define IDB_BITMAP2                     3010
#define IDC_PLUGNAME                    3011
#define IDD_SPHERE_DIALOG0              3012
#define IDD_SPHERE_DIALOG1              3013
#define IDD_SPHERE_DIALOG2              3014
#define IDD_CUSTOM_MATERIAL             3015
#define IDD_FLEXPORTER_MATERIAL         3016
#define IDC_EXPUVW                      3017
#define IDD_VERTEX_LIGHTER              3017
#define IDC_DISCARDW                    3018
#define IDC_EXPVTXCOL                   3019
#define IDC_USESMG                      3020
#define IDC_REMOVESCALING               3021
#define IDC_FORCEAMB                    3022
#define IDC_FORCEDIF                    3023
#define IDC_EXPCAMERAS                  3024
#define IDC_EXPCOMPLETE                 3037
#define IDC_CVTD3D                      3040
#define IDC_EXPLIGHTS                   3041
#define IDC_ABSOLUTEPRS                 3042
#define IDC_OPAINALPHA                  3043
#define IDC_TEXNAMEONLY                 3044
#define DC_KEEPTEXDSP                   3045
#define DC_KEEPTEXRFR                   3046
#define DC_KEEPTEXRFL                   3047
#define DC_KEEPTEXBUM                   3048
#define DC_KEEPTEXFIL                   3049
#define DC_KEEPTEXOPA                   3050
#define DC_KEEPTEXSLF                   3051
#define DC_KEEPTEXSTR                   3052
#define DC_KEEPTEXSHI                   3053
#define DC_KEEPTEXSPE                   3054
#define DC_KEEPTEXDIF                   3055
#define IDC_KEEPTEXAMB                  3056
#define IDC_MAXTEXSIZE                  3058
#define IDC_CONVEXHULL                  3059
#define IDC_BSPHERE                     3060
#define IDC_INERTIA                     3061
#define IDC_EXTENSION                   3062
#define IDC_VISTRACK                    3064
#define IDC_CONSOLIDATE                 3065
#define IDC_FACENORMALS                 3066
#define IDC_VTXNORMALS                  3067
#define IDC_EXPNORMINFO                 3068
#define IDC_LOADSETTINGS                3069
#define IDC_SAVESETTINGS                3070
#define IDC_MESSAGE                     3071
#define IDC_TARGET                      3072
#define IDC_EXPHIDDEN                   3073
#define IDC_EXP_BIPED                   3074
#define IDC_SLIDER1                     3075
#define IDC_SRATE                       3077
#define IDC_UPDATE                      3078
#define IDC_EDGEVIS                     3083
#define IDC_QUALITY                     3084
#define IDC_NBBITS                      3085
#define IDC_COMPRESSION                 3087
#define IDC_MANIFOLD                    3088
#define IDC_EXPSHAPES                   3089
#define IDC_EXPBIPED                    3090
#define IDC_FLIPH                       3091
#define IDC_FLIPV                       3092
#define IDC_WEIGHTBYAREA                3093
#define IDC_ALWAYSEXPORTMOTION          3094
#define IDC_MOTIONNAME                  3095
#define IDC_COMBOBOXEX1                 3096
#define IDC_QUANTIZE                    3097
#define IDC_FOVTRACK                    3098
#define IDC_EXPCAMCTRL                  3099
#define IDC_MTLANIM                     3100
#define IDC_EXPLITCTRL                  3101
#define IDC_EXPHELPERS                  3102
#define IDC_EXPPHYSIQUE                 3103
#define IDC_AUTOUNLOAD                  3104
#define IDC_SHAPETOMESH                 3105
#define IDC_FORCESPE                    3106
#define IDC_FORCEFIL                    3107
#define IDC_VERSION                     3108
#define IDC_NEWVERSION                  3112
#define IDC_AUTOLOAD                    3113
#define IDC_CACHEOPTIMIZE               3114
#define IDC_GLOBAL_SCALE                3116
#define IDC_EDIT1                       3117
#define IDC_MSG0                        3118
#define IDC_ADDUSERPROP                 3120
#define IDC_ABOUT_PLUG                  3121
#define IDC_DISCARD_INSTANCES           3122
#define IDC_PROJECTOR_MAPS              3123
#define IDC_EXPORT_IK                   3125
#define IDC_CREATEDIAMETER              3129
#define IDC_CREATERADIUS                3130
#define IDC_TI_POSX                     3131
#define IDC_TI_POSXSPIN                 3132
#define IDC_TI_POSY                     3133
#define IDC_TI_POSZ                     3134
#define IDC_TI_POSYSPIN                 3135
#define IDC_TI_POSZSPIN                 3136
#define IDC_RADIUS                      3137
#define IDC_RADSPINNER                  3138
#define IDC_TI_CREATE                   3139
#define IDC_SEGMENTS                    3142
#define IDC_SEGSPINNER                  3143
#define IDC_OBSMOOTH                    3144
#define IDC_HEMISPHERE                  3145
#define IDC_HEMISPHERESPINNER           3146
#define IDC_HEMI_CHOP                   3147
#define IDC_HEMI_SQUASH                 3148
#define IDC_SC_SLICEON                  3149
#define IDC_SC_SLICE1                   3150
#define IDC_SC_SLICE1SPIN               3151
#define IDC_SC_SLICE2                   3152
#define IDC_SC_SLICE2SPIN               3153
#define IDC_HEMI_RECENTER               3154
#define IDC_GENTEXTURE                  3155
#define IDC_LOCALE                      3156
#define IDC_EXPSKIN                     3157
#define IDC_MATERIAL_SHARING            3158
#define IDC_KEYFRAMING                  3161
#define IDC_SAMPLING                    3162
#define IDC_ALLFRAMES                   3163
#define IDC_SINGLEFRAME                 3164
#define IDC_SUBMAP                      3165
#define IDC_COLOR                       3166
#define IDC_CUSTOM_MATERIAL             3167
#define IDC_CHECKBOX                    3170
#define IDC_SPINNER                     3172
#define IDC_FILENAME                    3173
#define IDC_EDITTEXT                    3175
#define IDC_SHADER_FILENAME             3176
#define IDC_ADD_FLX_MATERIAL            3177
#define IDC_REMOVE_FLX_MATERIAL         3178
#define IDC_USER_PROPS                  3179
#define IDC_SCALE_SPINNER               3181
#define IDC_EXPWARP                     3182
#define IDC_DISCARD_ALPHA               3183
#define IDC_PRELIGHTER_SHADOWS          3184
#define IDC_COLOR_SMOOTHING             3185
#define IDC_PRECOMPUTE_LIGHTING         3186
#define IDC_PRELIGHTER_SPECULAR         3187
#define IDC_PRELIGHTER_CLAMP            3188
#define IDC_DECAL_TEXTURE               3189
#define IDC_DETAIL_TEXTURE              3190
#define IDC_BILLBOARD_TEXTURE           3191
#define IDC_AUTO_COPY_TEXTURES          3192

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        3020
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         3193
#define _APS_NEXT_SYMED_VALUE           3000
#endif
#endif
